### ISSUE TITLE
Date is not correctly validated when invalid date string is passed

### ISSUE THREAD

**Issue by Konosh93** [Konosh93/open-ts#17]
```yaml
MyRequestBody:
   required:
      - myDate
    properties:
       myDate:
          type: string
          format: date
```

This should fail if request body is like
```
   { "myDate": "" }
```

But instead, it passes and `Invalid Date` is created.
